SET SQL_SAFE_UPDATES=0;

SELECT * FROM FUNCIONARIO;

-- QUESTÃO A
UPDATE PACIENTE
SET CIDADE = 'JEQUIÉ'
WHERE NOME = 'PAULO';

-- QUESTÃO B 
UPDATE FUNCIONARIO
SET IDADE = IDADE+1;

-- QUESTÃO C
UPDATE MEDICO
SET CIDADE = 'ITAPETINGA'
WHERE cdAmb = 1;

SELECT CIDADE, CDAMB FROM MEDICO;

-- QUESTÃO D
UPDATE FUNCIONARIO
SET SALARIO = SALARIO*1.2
WHERE SALARIO <= 1500;

-- QUESTÃO E 
SELECT * FROM CONSULTA;

UPDATE CONSULTA
SET DATA = DATA+7
WHERE (CDMED = 2 and DATA+7 > CURRENT_DATE);

-- QUESTÃO F
UPDATE CONSULTA
SET HORA = '12:00'
WHERE (CDMED = 1 AND CDPAC = 4);

-- QUESTÃO G 
UPDATE PACIENTE
SET DOENCA = 'CÂNCER'
WHERE NOME = 'ANA';

SELECT * FROM PACIENTE;

-- LETRA H
UPDATE CONSULTA
SET OBS = 'CONFIRMADO'
WHERE CDMED = 1;

SELECT * FROM CONSULTA;

-- LETRA I
-- DELETE FROM FUNCIONARIO
-- WHERE NOME = 'CARLOS';

-- LETRA J
DELETE FROM CONSULTA
WHERE HORA > '19:00';

SELECT * FROM CONSULTA;

-- LETRA K 
DELETE FROM MEDICO
WHERE CIDADE = 'Salvador';

SELECT * FROM MEDICO;
