services:
  postgres-db:
    image: postgres:15
    container_name: postgres_tabd
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      - ./certs:/etc/postgresql/certs:ro
    command: [
      "postgres",
      "-c", "ssl=on",
      "-c", "ssl_ca_file=/etc/postgresql/certs/ca.pem",
      "-c", "ssl_cert_file=/etc/postgresql/certs/server-cert.pem",
      "-c", "ssl_key_file=/etc/postgresql/certs/server-key.pem"
    ]
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: lab_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
